<?php

namespace QCMBundle\Repository;

/**
 * istoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class istoryRepository extends \Doctrine\ORM\EntityRepository
{
}
