<?php

namespace QCMBundle\Repository;

/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMRepository extends \Doctrine\ORM\EntityRepository
{
}
